# -*- coding: utf-8 -*-
"""Matplotlib.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lnK3nFxOnM_Ri71ybAc9UKjEV-I5-G-x
"""

import matplotlib.pyplot as plt

import numpy as np
x  = np.arange(0,5)
y = x ** 2
print(x)
print(y)
plt.scatter(x,y)
plt.plot(x,y,'r')
plt.xlabel('X array ')
plt.ylabel('Y array')
plt.title("Title here: ")
plt.show()

import numpy as np
x  = np.arange(0,5)
y = x ** 2
print(x)
print(y)

#Now we will create bar ploting 
plt.bar(x,y)
plt.xlabel('X array ')
plt.ylabel('Y array')
plt.title("Title here: ")
plt.show()

#also can create scatter plote

plt.scatter(x,y)
plt.xlabel('X array ')
plt.ylabel('Y array')
plt.title("Title here: ")
plt.show()

year = [1972,1982,1986,2000,2010]
india = [100.3,20.4,55,33.2,33.3]
ban = [200.2,100.2,50.44,66.5,55]

plt.plot(year,india,color='orange',label="India")
plt.plot(year,ban,color='g',label="Bangladesh")

#naming x-axis and y-axis
plt.xlabel("Years")
plt.ylabel("Power consumption in kWh")
plt.title("Electricity consumption per capita\
 of India and Bangladesh")
plt.legend()  #eita na dile india bangladesh lekha dekha ba na orange and green
plt.show()

